CREATE DATABASE mytest;

CREATE TABLE t_user(
  userId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  userName VARCHAR(255) NOT NULL ,
  password VARCHAR(255) NOT NULL ,
  phone VARCHAR(255) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;
CREATE TABLE product(
  productId INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  productName VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  description TEXT,
  stock INT DEFAULT 0,
  mainImageUrl VARCHAR(255),
  imageUrl1 VARCHAR(255),
  imageUrl2 VARCHAR(255),
  imageUrl3 VARCHAR(255),
  imageUrl4 VARCHAR(255),
  imageUrl5 VARCHAR(255),
  category VARCHAR(100) NOT NULL DEFAULT 'General'
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;
CREATE TABLE cart (
  cartID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  userID INT NOT NULL,
  productID INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE (userID, productID),
  FOREIGN KEY (userID) REFERENCES user(user_id) ON DELETE CASCADE,
  FOREIGN KEY (productID) REFERENCES product(product_id)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;
